### ISSUE TITLE
Error while fetching https://robot.your- server.de/server: <urlopen error [Errno 101] Network is unreachable>

### ISSUE THREAD

**Issue by pratikbin** [ahaerpfer/ansible-inventory-hetzner-dedicated#3]
```yaml
plugin: hrobot

api_user: xxxx
api_password: xxxx

keyed_groups:
  - key: product | lower
    prefix: type
  - key: dc
    separator: ""
```

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/68642400/179343546-835c120f-6ed6-4132-80ae-5f54c4512fdd.png">
